version: '3.3'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5438:5432"
    env_file:
      - .env

  web:
    build: .
    restart: always
    ports:
      - "8888:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - .env