version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5438:5432"
    env_file:
      - .env

  web:
    build: ../drf_bookmarks/
    restart: always
    ports:
      - "8888:8000"
    volumes:
      - ../drf_bookmarks:/app
    depends_on:
      - db
    env_file:
      - .env
