name: Testing

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose up -d

    - name: Test with autotests
      run: |
        docker-compose run --rm --entrypoint "bash -c 'python3 manage.py test .'" web
