name: Testing

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose -f ../../infra/docker-compose.yml up -d

    - name: Test with autotests
      run: |
        docker-compose -f ../../infra/docker-compose.yml run --rm --entrypoint "bash -c 'python manage.py test'" web
